package io.github.krausstt.openbrowsertabs.core

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull

/** Expected values generated by the Python reference (tabs_pipeline.py). */
class CategorizerTest {

    private fun cat(url: String) = Categorizer.categorize(url)

    @Test
    fun `category mapping matches python reference`() {
        assertEquals("repo", cat("https://github.com/someorg/somerepo"))
        assertEquals("model_or_dataset", cat("https://huggingface.co/org/model-7b"))
        assertEquals("article", cat("https://heise.de/news/some-article-123.html"))
        assertEquals("blog", cat("https://medium.com/@author/some-post-1a2b3c"))
        assertEquals("shopping", cat("https://amazon.de/dp/B000000000"))
        assertEquals("discussion", cat("https://reddit.com/r/selfhosted/comments/xyz/title"))
        assertEquals("paper", cat("https://arxiv.org/abs/2601.12345"))
        assertEquals("docs", cat("https://docs.python.org/3/library/re.html"))
        assertEquals("video", cat("https://youtube.com/watch?v=abc123"))
        assertEquals("search_query", cat("https://google.com/search?q=esp32+audio+board"))
        assertEquals("travel", cat("https://airbnb.com/rooms/12345"))
        assertEquals("other", cat("https://example.com/a/b"))
    }

    @Test
    fun `search label extracts decoded query text`() {
        assertEquals(
            "esp32 audio board",
            Categorizer.searchLabel("https://google.com/search?q=esp32+audio+board&client=ms-android"),
        )
        assertNull(Categorizer.searchLabel("https://example.com/search?q=nope"))
    }

    @Test
    fun `topics match python reference`() {
        assertEquals(
            listOf("embedded_iot", "audio_music"),
            Categorizer.topics("https://google.com/search?q=esp32+audio+board&client=ms-android&oq=esp32"),
        )
        assertEquals(listOf("coding_devops"), Categorizer.topics("https://github.com/someorg/somerepo"))
        assertEquals(listOf("llm_agents"), Categorizer.topics("https://huggingface.co/org/model-7b"))
        assertEquals(listOf("untagged"), Categorizer.topics("https://example.com/a/b"))
    }
}
