package io.github.krausstt.openbrowsertabs.core

import java.net.URLEncoder

/**
 * URL splitting/normalization, ported 1:1 from pipeline/tabs_pipeline.py.
 * Parity is guarded by cross-validation tests whose expected values were
 * generated by the Python reference implementation.
 */
data class SplitUrl(
    val scheme: String,
    val netloc: String,
    val path: String,
    val query: String,
    val fragment: String,
)

fun urlsplit(url: String): SplitUrl {
    var s = url
    var fragment = ""
    val h = s.indexOf('#')
    if (h >= 0) {
        fragment = s.substring(h + 1)
        s = s.substring(0, h)
    }
    var scheme = ""
    var rest = s
    val i = s.indexOf("://")
    if (i > 0) {
        scheme = s.substring(0, i).lowercase()
        rest = s.substring(i + 3)
    }
    var query = ""
    val q = rest.indexOf('?')
    if (q >= 0) {
        query = rest.substring(q + 1)
        rest = rest.substring(0, q)
    }
    val slash = rest.indexOf('/')
    val netloc = if (slash >= 0) rest.substring(0, slash) else rest
    val path = if (slash >= 0) rest.substring(slash) else ""
    return SplitUrl(scheme, netloc, path, query, fragment)
}

/** Percent-decode; mirrors Python unquote (plusAsSpace=false) / unquote_plus (true). */
fun percentDecode(s: String, plusAsSpace: Boolean): String {
    val input = if (plusAsSpace) s.replace('+', ' ') else s
    val out = StringBuilder(input.length)
    val pending = ArrayList<Byte>() // consecutive %XX bytes form one UTF-8 sequence
    fun flush() {
        if (pending.isNotEmpty()) {
            out.append(String(pending.toByteArray(), Charsets.UTF_8))
            pending.clear()
        }
    }
    var i = 0
    while (i < input.length) {
        val c = input[i]
        if (c == '%' && i + 2 < input.length) {
            val v = input.substring(i + 1, i + 3).toIntOrNull(16)
            if (v != null) {
                pending.add(v.toByte())
                i += 3
                continue
            }
        }
        flush()
        out.append(c)
        i++
    }
    flush()
    return out.toString()
}

/** Mirrors Python parse_qsl(query, keep_blank_values=True). */
fun parseQsl(query: String): List<Pair<String, String>> =
    query.split('&')
        .filter { it.isNotEmpty() }
        .map { seg ->
            val eq = seg.indexOf('=')
            if (eq >= 0) {
                percentDecode(seg.substring(0, eq), plusAsSpace = true) to
                    percentDecode(seg.substring(eq + 1), plusAsSpace = true)
            } else {
                percentDecode(seg, plusAsSpace = true) to ""
            }
        }

/** Mirrors Python urlencode (quote_plus) closely enough for URL params. */
fun urlencode(pairs: List<Pair<String, String>>): String =
    pairs.joinToString("&") { (k, v) ->
        URLEncoder.encode(k, Charsets.UTF_8) + "=" + URLEncoder.encode(v, Charsets.UTF_8)
    }

object UrlNormalizer {

    // prefix families (utm_*, gad_*) or exact-match names — never bare
    // prefixes, otherwise "si" would also strip legitimate params like "size"
    private val TRACKING_PARAMS = Regex(
        "^(utm_|gad_" +
            "|(gclid|gbraid|wbraid|fbclid|mc_cid|mc_eid|igshid|si|ref_src" +
            "|PROVID|cmpid|smid|sh|ncid|guccounter|guce_referrer|_hsenc|_hsmi)$)",
        RegexOption.IGNORE_CASE,
    )
    private val AMP_HOST = Regex(
        "^(www[-.])?([a-z0-9-]+)\\.cdn\\.ampproject\\.org$",
        RegexOption.IGNORE_CASE,
    )
    private val AMP_LEFTOVERS = setOf("amp", "amp_gsa", "amp_js_v", "usqp")

    /** Recover the canonical URL from Google AMP-cache links. */
    fun unwrapAmp(url: String): String {
        val s = urlsplit(url)
        val ampPath = Regex("^/amp/s/(.+)$").find(s.path)
        if (s.netloc.lowercase().endsWith("google.com") && ampPath != null) {
            var rest = ampPath.groupValues[1]
            if (s.query.isNotEmpty()) rest += "?" + s.query
            return "https://" + rest.replace(Regex("\\.amp(?=$|\\?)"), "")
        }
        if (!AMP_HOST.matches(s.netloc)) return url
        for (blob in listOf(s.fragment, s.query)) {
            val m = Regex("ampshare=([^&]+)").find(blob)
            if (m != null) return percentDecode(m.groupValues[1], plusAsSpace = false)
        }
        val v = Regex("^/v/s/([^?#]+)").find(s.path)
        if (v != null) return "https://" + v.groupValues[1].replace(Regex("\\.amp$"), "")
        return url
    }

    fun normalize(url: String): String {
        val s = urlsplit(unwrapAmp(url))
        var host = s.netloc.lowercase()
        if (host.startsWith("www.")) host = host.substring(4)
        var q = parseQsl(s.query).filter { (k, _) -> TRACKING_PARAMS.find(k) == null }
        if (host.contains("youtube.com")) q = q.filter { it.first == "v" }
        q = q.filterNot { it.first in AMP_LEFTOVERS }
        var path = s.path.replace(Regex("\\.amp$"), "").trimEnd('/')
        if (path.isEmpty()) path = "/"
        path = path.replace(Regex("/amp$"), "")
        if (path.isEmpty()) path = "/"
        return buildString {
            append("https://").append(host).append(path)
            if (q.isNotEmpty()) append('?').append(urlencode(q))
        }
    }
}
